// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxpIO1zHIDY64QnY2RE5Fx2G-gg1YMFYM',
    appId: '1:149334414845:web:acbee5772fc9325d527594',
    messagingSenderId: '149334414845',
    projectId: 'newe-hub',
    authDomain: 'newe-hub.firebaseapp.com',
    storageBucket: 'newe-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrkxcnvF-wOFh5LVTzVe5EnmHV0ottLpk',
    appId: '1:149334414845:android:ec0e18daa53e9832527594',
    messagingSenderId: '149334414845',
    projectId: 'newe-hub',
    storageBucket: 'newe-hub.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxpIO1zHIDY64QnY2RE5Fx2G-gg1YMFYM',
    appId: '1:149334414845:web:9b459c150c15b459527594',
    messagingSenderId: '149334414845',
    projectId: 'newe-hub',
    authDomain: 'newe-hub.firebaseapp.com',
    storageBucket: 'newe-hub.firebasestorage.app',
  );
}
